fix(moon): changed to type specific return values and added moon test
SignalK/signalk-derived-data pull request #123
Opened 2023-11-26 17:42 UTC by godind

Fixes #122

Previous implementation retuned all moon path values as strings. Adjusted return types to correct types and added tests.

2023-12-07 09:09 UTC, tkurki requested changes
The moon values are numbers when coming from suncalc at https://github.com/SignalK/signalk-derived-data/blob/master/calcs/moon.js#L25. In this PR this plugin converts them first to strings and then back to numbers, in different parts of the code, that makes very little sense.

2023-12-07 09:09 UTC, tkurki commented on calcs/moon.js
> +          value: Boolean(times.alwaysDown ? 'true' : 'false')
alwaysUp and alwaysDown are either `true` Boolean or `undefined` coming from suncalc. Here you convert them first to string and then to Boolean. `value: !!times.alwaysDown` would do that trick in a much more concise way.

https://stackoverflow.com/questions/29312123/how-does-the-double-exclamation-work-in-javascript

2023-12-08 18:49 UTC, godind commented
You are most probably right! To be honest I was just trying to fix the output to get cleaner types and did not look deeper. But I added some tests! It's just a quick patch.

Do you need more work done or is it good for now?

2023-12-08 19:42 UTC, tkurki commented
Could you please fix the issues I pointed out.

2023-12-08 22:17 UTC, godind commented
No problem. I'll look at it.

2023-12-10 07:07 UTC, tkurki approved these changes

2023-12-10 10:54 UTC, tkurki requested changes
There are 2 failing tests on my machine:
```
       Sets environment.moon.* information such as phase, rise, and set[0] works:

      AssertionError: expected [ { …(2) }, { …(2) }, { …(2) }, …(5) ] to have the same json representation as [ { …(2) }, { …(2) }, { …(2) }, …(5) ]
      + expected - actual

           "value": 1.6
         }
         {
           "path": "environment.moon.times.rise"
      -    "value": "2017-04-15T02:59:40.750Z"
      +    "value": "2017-04-16T03:52:46.109Z"
         }
         {
           "path": "environment.moon.times.set"
      -    "value": "2017-04-15T13:26:01.692Z"
      +    "value": "2017-04-15T13:25:54.314Z"
         }
         {
           "path": "environment.moon.times.alwaysUp"
           "value": false
```

2023-12-10 22:23 UTC, godind commented
I'll check this out. I dont understand why the date changes every time in tests since it provides static input coordinates and date time.

Could it be that while running the tests, if the server is playing stream file, that it overrides the static test data?

2023-12-12 03:59 UTC, godind commented
I've fix the test issue, removed unnecessary variables, set default as undefined instead of `''`. See if this is acceptable.

Thanks!

2023-12-12 07:45 UTC, tkurki commented
There is no server involved in running the tests. I have no idea why the value would change, but the same tests still fail on my machine. Just remove the offending ones?

2023-12-14 01:01 UTC, godind commented
It should work fine. Looks good on my end.
```
derived data converts
    ✓ Magnetic Course Over Ground[0] works
    ✓ Magnetic Variation[0] works
    ✓ Magnetic Variation[1] works
    ✓ Sets environment.moon.* information such as phase, rise, and set[0] works
    ✓ propulsion.port.slip (propulsion.port.transmission.gearRatio, propulsion.port.drive.propeller.pitch)[0] works
    ✓ propulsion.port.slip (propulsion.port.transmission.gearRatio, propulsion.port.drive.propeller.pitch)[1] works
  6 passing (10ms)
```

2024-01-04 15:45 UTC, tkurki commented
It seems that the output varies for some reason, the tests fail on my machine

```
         {
           "path": "environment.moon.times.rise"
      -    "value": "2017-04-15T02:59:40.750Z"
      +    "value": "2017-04-16T03:52:46.109Z"
         }
         {
           "path": "environment.moon.times.set"
      -    "value": "2017-04-15T13:26:01.692Z"
      +    "value": "2017-04-15T13:25:54.314Z"
         }
```

Why don't you just remove the offending tests where the output varies for some reason? This PR does not change how the value is calculated, so this is a sidetrack.

Unless you want to really dig into what happens and fix things for all.

As long as the test fails I won't be merging this.

2024-01-15 00:08 UTC, godind reviewed
Done!

2024-01-21 19:51 UTC, tkurki commented
The test is failing, because the output contains properties not in the `expected` block. You would have spotted that if you had ran the tests.

2024-03-01 14:50 UTC, tkurki commented
Let's get this finished?

2024-03-23 02:46 UTC, godind reviewed
Removed ofending tests.

2024-03-23 02:47 UTC, godind reviewed
> Removed offending tests.

2024-04-17 19:46 UTC, godind commented
Do I still need to fix something? I don't see it if so...

Thanks

2024-04-19 05:18 UTC, merged